project:
  type: book

book:
  title: "Cookbook Polars for R"
  author: "Damien Dotta"
  favicon: logo_cookbook_rpolars.png
  description: A side-by-side comparison of polars, R base, dplyr, tidyr and data.table packages.
  keyword: polars, dplyr, tidyr, data.table, dataframe, performance, data science, data engineering
  url: https://ddotta.github.io/cookbook-rpolars/
  page-navigation: true
  sidebar: 
    logo: logo_cookbook_rpolars.png
    search: true
  repo-url: https://github.com/ddotta/cookbook-rpolars/
  repo-subdir: book
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  downloads: [pdf]
  image: polar-bear-airpods-no-background.png

  chapters:
    - index.qmd
    - first_steps.qmd
    - data_manipulation.qmd
    - import_export.qmd
    - lazy_execution.qmd
    - benchmarking.qmd

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    code-fold: false
    css: custom.css
    # mainfont: FiraCode
  # pdf:
  #   keep-tex: true
  #   documentclass: scrbook
  #   classoption: [paper=6in:9in,pagesize=pdftex,headinclude=on,footinclude=on,12pt]
  #   include-in-header:
  #     text: |
  #       \usepackage{inkscape}
  #       \usepackage{fvextra}
  #       \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
  #       \areaset[0.50in]{4.5in}{8in}
  #   include-before-body:
  #     text: |
  #       \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
  #          showspaces = false,
  #          showtabs = false,
  #          breaksymbolleft={},
  #          breaklines
  #          % Note: setting commandchars=\\\{\} here will cause an error 
  #       }  
  #   fig-pos: 'H'
